name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci

    - name: Configure env for Next.js (Appwrite)
      shell: bash
      run: |
        # Prefer GitHub Action Variables if provided; otherwise use sensible defaults
        : "${NEXT_PUBLIC_APPWRITE_ENDPOINT:=${{ vars.NEXT_PUBLIC_APPWRITE_ENDPOINT }}}"
        : "${NEXT_PUBLIC_APPWRITE_PROJECT_ID:=${{ vars.NEXT_PUBLIC_APPWRITE_PROJECT_ID }}}"
        if [ -z "$NEXT_PUBLIC_APPWRITE_ENDPOINT" ]; then NEXT_PUBLIC_APPWRITE_ENDPOINT="https://cloud.appwrite.io/v1"; fi
        if [ -z "$NEXT_PUBLIC_APPWRITE_PROJECT_ID" ]; then NEXT_PUBLIC_APPWRITE_PROJECT_ID="project-fra-6897812a000617c52694"; fi
        # Optional additional public IDs for DB/Collections/Buckets
        : "${NEXT_PUBLIC_APPWRITE_DATABASE_ID:=${{ vars.NEXT_PUBLIC_APPWRITE_DATABASE_ID }}}"
        : "${NEXT_PUBLIC_APPWRITE_CONTENTS_COLLECTION_ID:=${{ vars.NEXT_PUBLIC_APPWRITE_CONTENTS_COLLECTION_ID }}}"
        : "${NEXT_PUBLIC_APPWRITE_BUCKET_POSTERS_ID:=${{ vars.NEXT_PUBLIC_APPWRITE_BUCKET_POSTERS_ID }}}"
        : "${NEXT_PUBLIC_APPWRITE_BUCKET_VIDEOS_ID:=${{ vars.NEXT_PUBLIC_APPWRITE_BUCKET_VIDEOS_ID }}}"
        printf "NEXT_PUBLIC_APPWRITE_ENDPOINT=%s\nNEXT_PUBLIC_APPWRITE_PROJECT_ID=%s\nNEXT_PUBLIC_APPWRITE_DATABASE_ID=%s\nNEXT_PUBLIC_APPWRITE_CONTENTS_COLLECTION_ID=%s\nNEXT_PUBLIC_APPWRITE_BUCKET_POSTERS_ID=%s\nNEXT_PUBLIC_APPWRITE_BUCKET_VIDEOS_ID=%s\n" \
          "$NEXT_PUBLIC_APPWRITE_ENDPOINT" "$NEXT_PUBLIC_APPWRITE_PROJECT_ID" "$NEXT_PUBLIC_APPWRITE_DATABASE_ID" "$NEXT_PUBLIC_APPWRITE_CONTENTS_COLLECTION_ID" "$NEXT_PUBLIC_APPWRITE_BUCKET_POSTERS_ID" "$NEXT_PUBLIC_APPWRITE_BUCKET_VIDEOS_ID" > .env
        echo "Wrote .env with Appwrite config"
      
    - name: Build
      run: npm run build
    
    - name: Add .nojekyll
      run: touch out/.nojekyll
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./out
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 